### ISSUE TITLE
Provide friendly warning when bundler dependencies aren't installed

### ISSUE THREAD

**Issue by grant-olson** [grant-olson/BitMessageForum#33]
From the support line:

```
I'm getting this error after I performed a git pull before starting BMF today:
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- sanitize (LoadError)
from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
from /var/lib/gems/1.9.1/gems/backports-3.3.3/lib/backports/tools.rb:328:in `require_with_backports'
from ~/BitMessageForum/lib/bmf.rb:14:in `'
from ./bmf:3:in `require_relative'
```

If we don't have all the bundler dependencies, we should say something like:

```
"Couldn't find x.  Please run `bundle install` to install it.`
```

**Comment by grant-olson** [comment]
This has to be built in to bundler.  I'm probably just not calling something.
